// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/estoque": {
            "post": {
                "description": "Registra um novo estoque de fruta a partir do nome do fornecedor, nome da fruta e quantidade fornecida",
                "produces": [
                    "application/json"
                ],
                "summary": "Registra uma nova fruta em estoque a partir do nome do fornecedor, nome da fruta e quantidade fornecida",
                "operationId": "post-estoque",
                "parameters": [
                    {
                        "type": "string",
                        "description": "NomeFruta",
                        "name": "nomeFruta",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "NomeFornecedor",
                        "name": "nomeFornecedor",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Quantidade",
                        "name": "quantidade",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Estoque de fruta registrado com sucesso",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Informaçōes inválidas.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Uma fruta com esse nome já existe.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Falha ao registrar Fruta. Por favor, tente novamente",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/estoque/{nomeFruta}/{nomeFornecedor}": {
            "get": {
                "description": "Busca a quantidade de uma fruta fornecida por um fornecedor no estoque a partir do nome da fruta e nome do fornecedor",
                "produces": [
                    "application/json"
                ],
                "summary": "Busca a quantidade de uma fruta fornecida por um fornecedor no estoque a partir do nome da fruta e nome do fornecedor",
                "operationId": "get-estoque",
                "parameters": [
                    {
                        "type": "string",
                        "description": "nomeFruta",
                        "name": "nomeFruta",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "nomeFornecedor",
                        "name": "nomeFruta",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Retorna as informaçōes do estoque da Fruta",
                        "schema": {
                            "$ref": "#/definitions/model.Estoque"
                        }
                    },
                    "400": {
                        "description": "O nome da fruta não deve ser vazio, e pode conter no máximo 50 caracteres",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Fruta não encontrada em Estoque",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/fornecedor": {
            "post": {
                "description": "Registra um novo fornecedor a partir do seu nome e telefone",
                "produces": [
                    "application/json"
                ],
                "summary": "Registra um novo fornecedor no sistema a partir de suas informaçōes",
                "operationId": "post-fornecedor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nome",
                        "name": "nome",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Telefone",
                        "name": "telefone",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Fornecedor registrado com sucesso",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Informaçōes inválidas.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Um fornecedor com esse nome já existe.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Falha ao registrar Fornecedor. Por favor, tente novamente",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/fornecedor/{nome}": {
            "get": {
                "description": "Retorna as informaçōes de um fornecedor a partir de seu nome",
                "produces": [
                    "application/json"
                ],
                "summary": "Busca um fornecedor pelo nome",
                "operationId": "get-fornecedor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "nome",
                        "name": "nome",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Retorna as informaçōes do fornecedor",
                        "schema": {
                            "$ref": "#/definitions/model.Fornecedor"
                        }
                    },
                    "400": {
                        "description": "O nome do fornecedor não deve ser vazio, e pode conter no máximo 50 caracteres",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Fornecedor não encontrado",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/fruta": {
            "post": {
                "description": "Registra uma nova fruta a partir do seu nome e preco",
                "produces": [
                    "application/json"
                ],
                "summary": "Registra uma nova fruta no sistema a partir de suas informaçōes",
                "operationId": "post-fruta",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nome",
                        "name": "nome",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Preco",
                        "name": "preco",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Fruta registrada com sucesso",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Informaçōes inválidas.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Uma fruta com esse nome já existe.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Falha ao registrar Fruta. Por favor, tente novamente",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/fruta/{nome}": {
            "get": {
                "description": "Retorna as informaçōes de uma fruta a partir de seu nome",
                "produces": [
                    "application/json"
                ],
                "summary": "Busca por uma fruta pelo nome",
                "operationId": "get-fruta",
                "parameters": [
                    {
                        "type": "string",
                        "description": "nome",
                        "name": "nome",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Retorna as informaçōes da fruta",
                        "schema": {
                            "$ref": "#/definitions/model.Fruta"
                        }
                    },
                    "400": {
                        "description": "O nome da fruta não deve ser vazio, e pode conter no máximo 50 caracteres",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Fruta não encontrada",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Estoque": {
            "type": "object",
            "properties": {
                "nomeFornecedor": {
                    "type": "string"
                },
                "nomeFruta": {
                    "type": "string"
                },
                "quantidade": {
                    "type": "integer"
                }
            }
        },
        "model.Fornecedor": {
            "type": "object",
            "properties": {
                "nome": {
                    "type": "string"
                },
                "telefone": {
                    "type": "string"
                }
            }
        },
        "model.Fruta": {
            "type": "object",
            "properties": {
                "nome": {
                    "type": "string"
                },
                "preco": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
